export const projects = [
  {
    id: "331",
    name: "MoneyOnChain",
    slug: "moneyonchain",
    symbol: "MOC",
    address: "rsk:0x9AC7fE28967B30E3A4e6e03286d715b42B453D10",
    url: "https://moneyonchain.com/",
    description:
      "Money On Chain is a self-contained DeFi protocol (a stablecoin, HODL token, leveraging mechanism, and more) which empowers Bitcoiners to improve performance of their assets while also retaining full control of their private keys.",
    chain: "RSK",
    category: "Decentralized Stablecoin",
    twitter: "moneyonchainok",
    mcap: 0,
    tvl: "$518.98m",
    change_1m: "+10.02%",
  },
  {
    id: "parent#sovryn",
    name: "Sovryn",
    slug: "sovryn",
    url: "https://sovryn.com/",
    description:
      "Sovryn is a non-custodial and permission-less smart contract based system for bitcoin lending, borrowing and margin trading.",
    twitter: "SovrynBTC",
    mcap: 30466777.864859335,
    tvl: "$72.66m",
    change_1m: "+9.02%",
  },
  {
    id: "4020",
    name: "RIF ON CHAIN",
    slug: "rif-on-chain",
    url: "https://rifonchain.com/",
    description:
      "RIF On Chain offers a censorship-resistant stablecoin protocol on Rootstock, enabling users to mint USDRIF, a fully crypto-collateralized stablecoin, and RIF PRO, a leveraged token for RIF holders and traders",
    chain: "RSK",
    category: "Decentralized Stablecoin",
    twitter: "rifonchain",
    mcap: null,
    tvl: "$14.35m",
    change_1m: "+2.74%",
  },
  {
    id: "2198",
    name: "Uniswap V3",
    slug: "uniswap-v3",
    symbol: "UNI",
    address: "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
    url: "https://uniswap.org/",
    description:
      "A fully decentralized protocol for automated liquidity provision on Ethereum. V2\r\n",
    chain: "Ethereum",
    category: "Dexes",
    twitter: "Uniswap",
    mcap: null,
    tvl: "$10.09m",
    change_1m: "+8.58%",
  },
  {
    id: "1464",
    name: "Tropykus RSK",
    slug: "tropykus-rsk",
    url: "https://app.tropykus.com",
    description:
      "Tropykus is a DeFi for Bitcoin lending and borrowing platform focused on Latanamerica.",
    chain: "RSK",
    category: "Lending",
    twitter: "tropykus",
    mcap: null,
    tvl: "$6.2m",
    change_1m: "+9.79%",
  },
  {
    id: "parent#sushi",
    name: "Sushi",
    slug: "sushi",
    symbol: "SUSHI",
    url: "https://sushi.com/",
    description:
      "A fully decentralized protocol for automated liquidity provision on Ethereum.\r\n",
    twitter: "SushiSwap",
    mcap: 162224805.41520268,
    tvl: "$3.17m",
    change_1m: "+6.88%",
  },
  {
    id: "326",
    name: "Beefy",
    slug: "beefy",
    symbol: "BIFI",
    address: "0xB1F1ee126e9c96231Cc3d3fAD7C08b4cf873b1f1",
    url: "https://beefy.com",
    description:
      "Beefy automates yield farming to make DeFi easy, safe and efficient for all. By autocompounding your tokens, Beefy unlocks higher returns so you earn more of what you love.",
    chain: "Binance",
    category: "Yield Aggregator",
    twitter: "beefyfinance",
    mcap: 26185669.524047256,
    tvl: "$849,141",
    change_1m: "+12.97%",
  },
  {
    id: "355",
    name: "Gamma",
    slug: "gamma",
    symbol: "GAMMA",
    address: "0x6bea7cfef803d1e3d5f7c0103f7ded065644e197",
    url: "https://www.gamma.xyz",
    description:
      "A protocol for active liquidity management and market-making strategies. Gamma offers non-custodial, automated, and active concentrated liquidity management services.",
    chain: "Ethereum",
    category: "Liquidity manager",
    twitter: "GammaStrategies",
    mcap: 4989809.702096461,
    tvl: "$304,108",
    change_1m: "+4.93%",
  },
  {
    id: "4816",
    name: "WoodSwap",
    slug: "woodswap",
    url: "https://woodswap.org",
    description: "A fast, secure, and seamless DEX rooted in Rootstock BTC L2",
    chain: "RSK",
    category: "Dexes",
    twitter: "woodswap_org",
    mcap: null,
    tvl: "$276,854",
    change_1m: "+3.24%",
  },
  {
    id: "3043",
    name: "Steer Protocol",
    slug: "steer-protocol",
    url: "https://steer.finance",
    description:
      "Steer is a decentralized compute protocol that provides a scaling solution for data processing through its robust off-chain infrastructure. Services are targeted at leveraging off-chain data for on-chain automation, such as automated liquidity management in DeFi.",
    chain: "Polygon",
    category: "Liquidity manager",
    twitter: "steerprotocol",
    mcap: null,
    tvl: "$251,856",
    change_1m: "-0.58%",
  },
  {
    id: "1594",
    name: "Symbiosis",
    slug: "symbiosis",
    symbol: "SIS",
    address: "0xd38bb40815d2b0c2d2c866e0c72c5728ffc76dd9",
    url: "https://symbiosis.finance",
    description:
      "Symbiosis aggregates decentralized exchange liquidity across any EVM and non-EVM networks. Swap any token and transfer liquidity. Yes, any.",
    chain: "Ethereum",
    category: "Cross Chain",
    twitter: "symbiosis_fi",
    mcap: 7891733.160529869,
    tvl: "$209,615",
    change_1m: "+27.81%",
  },
  {
    id: "674",
    name: "RskSwap",
    slug: "rskswap",
    url: "https://rskswap.com",
    description:
      "RSK Swap is a fork of the Uniswap Protocol adapted for the RSK network.",
    chain: "RSK",
    category: "Dexes",
    twitter: "RskSwap",
    mcap: null,
    tvl: "$79,912",
    change_1m: "+4.66%",
  },
  {
    id: "4109",
    name: "Segment Finance",
    slug: "segment-finance",
    symbol: "SEF",
    address: "bsc:0x5de40c1152c990492eaeaeecc4ecaab788bbc4fd",
    url: "https://segment.finance",
    description:
      "Segment Finance is a decentralized lending and borrowing platform built on BNB Chain.",
    chain: "Binance",
    category: "Lending",
    twitter: "segment_fi",
    mcap: 0,
    tvl: "$38,413",
    change_1m: "+0.01%",
  },
  {
    id: "420",
    name: "Elk",
    slug: "elk",
    symbol: "ELK",
    address: "0xeEeEEb57642040bE42185f49C52F7E9B38f8eeeE",
    url: "https://elk.finance",
    description:
      "Elk Finance is building Web3 infrastructure for cross-chain value and data transfer via ElkNet - our decentralized bridge. Our motto is Any chain, anytime, anywhere.",
    chain: "Polygon",
    category: "Dexes",
    twitter: "elk_finance",
    mcap: 1425521.020960568,
    tvl: "$38,707",
    change_1m: "+8.16%",
  },
  {
    id: "1528",
    name: "Blindex",
    slug: "blindex",
    symbol: "BDX",
    address: "rsk:0x6542a10E68cEAc1Fa0641ec0D799a7492795AAC1",
    url: "https://blindex.io/",
    description:
      "Blindex is a multi-currency stablecoin DeFi platform. Mint, swap, trade, invest and redeem any FX-pegged coin.All coins are partially collateralized, algorithmically stabilized and completely decentralized.",
    chain: "RSK",
    category: "Algo-Stables",
    twitter: "BlinDEXio",
    mcap: null,
    tvl: "$33,538",
    change_1m: "+3.85%",
  },
  {
    id: "627",
    name: "Balmy",
    slug: "balmy",
    url: "https://balmy.xyz",
    description:
      "Balmy is your home for accessing the world of decentralized finance as it was meant to be: safe, open, and intuitive. Swap your assets at the best price, make recurring investments into your favorite tokens, or transfer money easily — all in one place that meets your immediate financial needs and sets you up for long-term success.",
    chain: "Ethereum",
    category: "Services",
    twitter: "balmy_xyz",
    mcap: null,
    tvl: "$533.09",
    change_1m: "+6.87%",
  },
  {
    id: "4696",
    name: "Pell Network",
    slug: "pell-network",
    url: "https://pell.network/",
    description:
      "Pell uses BTC and its LSD to provide actively validated services (AVS) to BTC ecosystem projects, plug the gap in ecosystem security, reduce cost to develop ecosystem applications and optimise yield avenue for BTC holders. Pell aims to become the largest shared liquidity and cryptonomic security layer in the BTC ecosystem across market cycles",
    chain: "Merlin",
    category: "Restaking",
    twitter: "Pell_Network",
    mcap: null,
    tvl: "$17.69",
    change_1m: "+9.77%",
  },
  {
    id: "533",
    name: "OpenOcean",
    slug: "openocean",
    symbol: "OOE",
    address: "bsc:0x8ea5219a16c2dbf1d6335a6aa0c6bd45c50347c5",
    url: "https://openocean.finance",
    description:
      "OpenOcean is the world's first full aggregation protocol for crypto trading that source liquidity from DeFi and CeFi, and enable cross-chain swaps.",
    chain: "Binance",
    category: "DEX Aggregator",
    twitter: "OpenOceanGlobal",
    mcap: 4260539.917658699,
    tvl: "$0",
    change_1m: null,
  },
  {
    id: "5184",
    name: "Rootstock Collective",
    slug: "rootstock-collective",
    url: "https://rootstockcollective.xyz",
    description:
      "RootstockCollective is a DAO (Decentralized Autonomous Organization) designed to develop the Rootstock ecosystem by empowering and rewarding builders and users of Rootstock, and RIF token holders",
    chain: "RSK",
    category: "Governance Incentives",
    twitter: "RootstockColl",
    mcap: null,
    tvl: "$0",
    change_1m: null,
  },
];
